Fix beneficiary expelled
TakafulDAO/takaturn pull request #125
Opened 2023-10-09 17:35 UTC by maikelordaz

Also create a new hardhat task to get the fund summary, this to be able to track in a better way the bug

2023-10-09 17:36 UTC, maikelordaz commented
related to git issue #124

2023-10-10 06:17 UTC, MohammedTaka requested changes
Please add an extra unit tests that checks if OnCollateralLiquidated DOES NOT trigger. Also a check if the collateral of the beneficiary remains the same. Collateral before closeFundingPeriod should be the same as after closeFundingPeriod

2023-10-10 06:51 UTC, maikelordaz commented
Added the unit test checking the collateral before and after closeFundingPeriod

2023-10-10 07:26 UTC, MohammedTaka approved these changes

2023-10-10 07:26 UTC, merged