Yield getters
TakafulDAO/takaturn pull request #159
Opened 2023-11-06 02:41 UTC by maikelordaz

Git issue #157

2023-11-07 18:59 UTC, MohammedTaka requested changes

2023-11-07 18:59 UTC, MohammedTaka commented on contracts/facets/GettersFacet.sol
> +        if (termBalance * pricePerShare > yield.currentTotalDeposit) {
termBalance * pricePerShare is used twice

This can be a variable and reused

2023-11-07 18:59 UTC, MohammedTaka commented on contracts/facets/GettersFacet.sol
> +        if (termBalance * pricePerShare > yield.currentTotalDeposit) {
termBalance * pricePerShare is 18 decimals * 18 decimals. It must be divided by 18 decimals to get the eth value

2023-11-07 18:59 UTC, MohammedTaka commented on contracts/facets/GettersFacet.sol
> +            uint currentSharesPrice = (termBalance * pricePerShare) / 10 ** 18;
Formula is correct but the variable name is weird. Can make it sharesInEth as name

2023-11-07 18:59 UTC, MohammedTaka commented on test/fork/03-yield-generation-getters.test.js
> +                  it("After some withdraws", async function () {
Here the user defaults AND withdraws. Might be good to also have an it that has the user pay the contribution so no defaulting takes place, and then do a manual withdraw

2023-11-07 18:59 UTC, MohammedTaka commented on test/fork/03-yield-generation-getters.test.js
> +                      assert.equal(termAPYBefore.toString(), 0)
Why are these 0? The term APY should show the apy even without withdrawals

2023-11-08 12:00 UTC, maikelordaz commented on contracts/facets/GettersFacet.sol
> +        if (termBalance * pricePerShare > yield.currentTotalDeposit) {
Commit b7c90a2

2023-11-08 12:07 UTC, maikelordaz commented on contracts/facets/GettersFacet.sol
> +        if (termBalance * pricePerShare > yield.currentTotalDeposit) {
Commit 71aec09

2023-11-08 12:08 UTC, maikelordaz commented on contracts/facets/GettersFacet.sol
> +            uint currentSharesPrice = (termBalance * pricePerShare) / 10 ** 18;
Commit cf1c259

2023-11-08 12:48 UTC, maikelordaz commented on test/fork/03-yield-generation-getters.test.js
> +                      assert.equal(termAPYBefore.toString(), 0)
Commit 20e1399

2023-11-08 13:13 UTC, maikelordaz commented on test/fork/03-yield-generation-getters.test.js
> +                  it("After some withdraws", async function () {
Commits 021e1d2 and 7365ffd

2023-11-08 13:14 UTC, maikelordaz commented
@MohammedTaka done with the comments reviews. You can check again

2023-11-12 10:46 UTC, MohammedTaka reviewed
Some comments on tests, smart contract logic seems correct however

2023-11-12 10:46 UTC, MohammedTaka commented on test/fork/03-yield-generation-getters.test.js
> +                              yieldDistributionRatioBefore.toString() <
Wait a second, shouldn't this check be reversed? An user's yieldDistributionRatio should become LESS if he withdraws

2023-11-12 10:46 UTC, MohammedTaka commented on test/fork/03-yield-generation-getters.test.js
> +                                  yieldDistributionRatioAfter.toString()
You are comparing strings here, is that correct? Shouldn't it be BigNumber?

2023-11-12 16:33 UTC, maikelordaz commented on test/fork/03-yield-generation-getters.test.js
> +                                  yieldDistributionRatioAfter.toString()
Yes as I'm not doing any math is ok only to compare without using BigNumber. This is just because JS is weakly typed

2023-11-12 16:44 UTC, maikelordaz commented on test/fork/03-yield-generation-getters.test.js
> +                              yieldDistributionRatioBefore.toString() <
On the formula the yieldDistributionRatio it is inversely proportional to the currentTotalDeposit. Maybe the formula on the function is wrong?.

2023-11-12 16:45 UTC, maikelordaz commented on test/fork/03-yield-generation-getters.test.js
> +                              yieldDistributionRatioBefore.toString() <
Right now it is
```solidity
return (yield.depositedCollateralByUser[user] * 10 ** 18) / yield.currentTotalDeposit;
```
Shouldn't be?
```
return (collateral.collateralMembersBank[user] * 10 ** 18) / yield.currentTotalDeposit;
```

2023-11-12 16:54 UTC, maikelordaz commented on test/fork/03-yield-generation-getters.test.js
> +                              yieldDistributionRatioBefore.toString() <
I've made 
```solidity
return
                ((yield.depositedCollateralByUser[user] - yield.withdrawnCollateral[user]) *
                    10 ** 18) / yield.currentTotalDeposit;
```

Commit c801639 and tests on commit 975cdd1

2023-11-12 17:18 UTC, maikelordaz commented
@MohammedTaka You can review again

2023-11-16 18:18 UTC, maikelordaz commented on test/fork/03-yield-generation-getters.test.js
> +                              yieldDistributionRatioBefore.toString() <
@MohammedTaka can you check this please? I changed the formula

2023-11-16 19:24 UTC, maikelordaz commented
@MohammedTaka I marked the conversations as resolved except one comment about a change I made on the yieldDistributionRatio, please check.

Added one more test to it
Current coverage 
<img width="527" alt="image" src="https://github.com/TakafulDAO/takaturn-phase-2/assets/98809476/63f72c67-1a0c-454a-bf47-a2d0c6ffd794">

The lines and functions on the term and yield facets are covered but on forked tests, so it does not show in this table

2023-11-16 20:58 UTC, MohammedTaka approved these changes

2023-11-16 20:58 UTC, MohammedTaka commented on test/fork/03-yield-generation-getters.test.js
> +                              userYieldGeneratedBefore.toString() >
Yield generated after should be greater than yield generated before

2023-11-16 20:58 UTC, MohammedTaka commented on test/fork/03-yield-generation-getters.test.js
> +                              userYieldGeneratedBefore.toString() >
Same here

2023-11-16 20:58 UTC, MohammedTaka commented on test/fork/03-yield-generation-getters.test.js
> +                              yieldDistributionRatioBefore.toString() <
This is correct

2023-11-16 20:58 UTC, merged