Add function to transfer balance to address
TakafulDAO/takaturn pull request #181
Opened 2023-12-23 02:34 UTC by maikelordaz

2024-01-02 08:44 UTC, MohammedTaka requested changes

2024-01-02 08:44 UTC, MohammedTaka commented on contracts/facets/CollateralFacet.sol
>      event OnReimbursementWithdrawn(uint indexed termId, address indexed user, uint indexed amount);
Should this not also have a receiver now?

2024-01-02 08:44 UTC, MohammedTaka commented on contracts/facets/YGFacetZaynFi.sol
> +        LibYieldGeneration._claimAvailableYield(termId, msg.sender, msg.sender);
Should there be a receiver input in the event if it's always msg.sender?

2024-01-02 08:44 UTC, MohammedTaka commented on test/unit/02-combined-tests/combined.test.js
> +                  it("allows the beneficiary to claim the fund to a different address", async function () {
Please also do a test for withdrawing collateral

2024-01-08 00:37 UTC, maikelordaz commented on contracts/facets/CollateralFacet.sol
>      event OnReimbursementWithdrawn(uint indexed termId, address indexed user, uint indexed amount);
You are right, missed it. Fix it on commit 3a8204f and fix tests on commit 8c15233

2024-01-08 01:13 UTC, maikelordaz commented on contracts/facets/YGFacetZaynFi.sol
> +        LibYieldGeneration._claimAvailableYield(termId, msg.sender, msg.sender);
Fix on commit 2c652ea
Test on commit cbe5fc6

2024-01-08 01:19 UTC, maikelordaz commented on test/unit/02-combined-tests/combined.test.js
> +                  it("allows the beneficiary to claim the fund to a different address", async function () {
It is on https://github.com/TakafulDAO/takaturn-phase-2/blob/cbe5fc64276858d8a6d75dc5cc402de7212ea262/test/unit/01-by-facet/02-collateral-facet.test.js#L219

2024-01-09 16:49 UTC, MohammedTaka approved these changes

2024-01-09 18:46 UTC, merged