Multisig
TakafulDAO/takaturn pull request #183
Opened 2023-12-27 01:42 UTC by maikelordaz

Please review this PR at last, this because there is a big package migration and can interfere with the other PRs

Migrations:
- The biggest migration it is done from ethers v5 to ethers v6 following [this](https://[docs.ethers.org/v6/migrating/](https://docs.ethers.org/v6/migrating/)) and some github issues, this does not affect the contracts ony the tests and scripts
- Some packages were removed and the others were updated
- Openzeppelin contracts were not updated because the new version uses Namespace storage this conflicts with previous pattern. An article about can be read [here](https://medium.com/51nodes/why-upgrading-openzeppelin-smart-contracts-from-version-4-to-version-5-is-unsafe-e08be30efd8a)

The migrations were made to be able to use the SafeApiKit from Safe multisig or Openzeppelin Defender in the future to automate the process when creating the upgrade proposals

2024-01-02 09:07 UTC, MohammedTaka requested changes
I see many tests failing. Those need to be resolved

2024-01-08 01:43 UTC, maikelordaz commented
> I see many tests failing. Those need to be resolved

I don't have any test failing, maybe we can check on the tuesday call

2024-01-09 16:50 UTC, MohammedTaka approved these changes

2024-01-09 16:50 UTC, MohammedTaka commented
Approved, there's still a to-do to define a multisig sign process

2024-01-09 20:15 UTC, merged