update CI/CD
TakafulDAO/takaturn pull request #194
Opened 2024-02-26 22:28 UTC by maikelordaz

2024-02-27 15:34 UTC, elallamTaka approved these changes

2024-02-29 01:17 UTC, maikelordaz commented
@elallamTaka commit 75f1232 worked to commit the ABIs on push. I'm changing it again to work only on approval reviews, please check again

2024-02-29 01:26 UTC, maikelordaz commented
Done. Should work now @elallamTaka , it worked fine on commit ebaa45e and 75f1232, for that ones I changed it to work when push. It is set now to when a review is approved

2024-02-29 09:31 UTC, elallamTaka requested changes

2024-02-29 09:31 UTC, elallamTaka commented on .github/workflows/02-sc_testnet_deploy_cd.yml
>              echo "::set-output name=branch::${{ github.head_ref }}"
forgot to revise set-output here

2024-02-29 11:37 UTC, maikelordaz commented on .github/workflows/02-sc_testnet_deploy_cd.yml
>              echo "::set-output name=branch::${{ github.head_ref }}"
Commit b03b480

2024-03-03 11:52 UTC, elallamTaka approved these changes

2024-03-03 12:41 UTC, elallamTaka approved these changes

2024-03-03 13:11 UTC, elallamTaka approved these changes

2024-03-03 13:24 UTC, elallamTaka approved these changes

2024-03-05 11:07 UTC, elallamTaka approved these changes

2024-03-06 06:03 UTC, elallamTaka approved these changes

2024-03-06 12:04 UTC, maikelordaz commented
rerun prints

2024-03-06 12:07 UTC, maikelordaz commented
rerun prints

2024-03-06 18:11 UTC, maikelordaz commented
/upgrade-abis

2024-03-06 18:13 UTC, maikelordaz commented
/upgrade-abis

2024-03-06 18:18 UTC, maikelordaz commented
/upgrade-abis

2024-03-06 18:23 UTC, maikelordaz commented
/upgrade-abis

2024-03-06 18:26 UTC, maikelordaz commented
/upgrade-abis

2024-03-06 18:28 UTC, maikelordaz commented
/upgrade-abis

2024-03-09 16:28 UTC, elallamTaka approved these changes

2024-03-09 16:33 UTC, merged