Pay security deposit on behalf of
TakafulDAO/takaturn pull request #197
Opened 2024-03-07 02:17 UTC by maikelordaz

2024-03-07 08:08 UTC, MohammedTaka approved these changes

2024-03-09 18:51 UTC, elallamTaka requested changes

2024-03-09 18:51 UTC, elallamTaka commented on contracts/facets/TermFacet.sol
> +    event OnCollateralDeposited(
Add the a new param to identify the address who paid on behalf of

2024-03-09 21:02 UTC, maikelordaz commented on contracts/facets/TermFacet.sol
> +    event OnCollateralDeposited(
Commit a033f65 and tests on ed02182

2024-03-10 16:50 UTC, elallamTaka approved these changes

2024-03-10 16:56 UTC, merged