chore: require statements error codes
TakafulDAO/takaturn pull request #203
Opened 2024-03-26 01:01 UTC by maikelordaz

In this PR I changed all the require strings for code errors, this way we have the next improvements
- Save gas on calls as the strings are shorter
- Save gas on deploy as the strings are shorter
- Can help debugging errors, now we can now exactly if an error string come from our source code, or from an external
- Can help customer support as they can have a document explaining each error
- Can help BE and FE implementation as they can now exactly what is happening

2024-03-26 09:09 UTC, elallamTaka requested changes
Neat, please add a docs folder wth the error codes in .md format

2024-03-26 20:21 UTC, maikelordaz commented
@elallamTaka pushed the markdown with the error codes on commit 4bcbb71

2024-03-27 08:16 UTC, elallamTaka approved these changes

2024-03-28 16:37 UTC, MohammedTaka approved these changes

2024-03-28 16:49 UTC, merged